"""意图相关提示词模块"""
from app.prompts.intents.recognition import INTENT_RECOGNITION_SYSTEM, INTENT_RECOGNITION_USER_TEMPLATE
from app.prompts.intents.contract import CONTRACT_GENERATION_SYSTEM, LEASE_CONTRACT_PROMPT, LABOR_CONTRACT_PROMPT

__all__ = [
    'INTENT_RECOGNITION_SYSTEM',
    'INTENT_RECOGNITION_USER_TEMPLATE',
    'CONTRACT_GENERATION_SYSTEM',
    'LEASE_CONTRACT_PROMPT',
    'LABOR_CONTRACT_PROMPT',
]
